name: Bump submodules

on:
  workflow_dispatch:
    inputs:
      branch-name:
        default: "bump-submodule"
        type: string
        description: "Branch name to use for the PR"
  schedule:
    - cron: "0 11 * * 1"

permissions:
  contents: write
  pull-requests: write

env:
  GIT_BRANCH_NAME: ${{ inputs.branch-name || 'bump-submodule' }}

jobs:
  bump-submodules:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.12'
      
      - name: Configure Git Identity
        run: |
          git config --global user.name "therockbot"
          git config --global user.email "therockbot@amd.com"

      - name: Run bump_submodules.py
        run: |
          python3 ./build_tools/bump_submodules.py \
            --create-branch \
            --branch-name ${{ env.GIT_BRANCH_NAME }} \
            --components profiler

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.CREATE_PULL_REQUEST_TOKEN_APP_ID }}
          private-key: ${{ secrets.CREATE_PULL_REQUEST_TOKEN_APP_PRIVATE_KEY }}

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base: main
          branch: ${{ env.GIT_BRANCH_NAME }}
          title: "Weekly Submodule Bump"
          body: |
            This PR was automatically created by a GitHub App to update submodules.
          commit-message: "Automated submodule bump"
          signoff: true
