name: CI - Linux

on:
  workflow_call:
    inputs:
      amdgpu_families:
        type: string
      artifact_run_id:
        type: string
      test_runs_on:
        type: string
      expect_failure:
        type: boolean
      use_prebuilt_artifacts:
        type: string

permissions:
  contents: read

jobs:
  build_portable_linux_artifacts:
    name: Build
    if: ${{ inputs.use_prebuilt_artifacts == 'false' }}
    uses: ./.github/workflows/build_portable_linux_artifacts.yml
    secrets: inherit
    with:
      amdgpu_families: ${{ inputs.amdgpu_families }}
      expect_failure: ${{ inputs.expect_failure }}
    permissions:
      contents: read
      id-token: write

  test_linux_artifacts:
    needs: [build_portable_linux_artifacts]
    name: Test
    # If the dependent job failed/cancelled, this job will not be run
    # The use_prebuilt_artifacts "or" statement ensures that tests will run if previous build step is run or skipped.concurrency.
    if: >-
      ${{
        !failure() &&
        !cancelled() &&
        (
          inputs.use_prebuilt_artifacts == 'false' ||
          inputs.use_prebuilt_artifacts == 'true'
        )
      }}
    strategy:
      fail-fast: false
    uses: ./.github/workflows/test_artifacts.yml
    with:
      amdgpu_families: ${{ inputs.amdgpu_families }}
      test_runs_on: ${{ inputs.test_runs_on }}
      artifact_run_id: ${{ inputs.artifact_run_id }}
